version: "3.9"

volumes:
  prod_database_data:

services:
  # discord:
  #   build: .

  database:
    image: mysql/mysql-server
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_DATABASE=vylbot
      - MYSQL_USER=prod
      - MYSQL_PASSWORD=prod
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_ROOT_HOST=0.0.0.0
    ports:
      - "3121:3306"
    volumes:
      - prod_database_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - "3122:80"
    environment:
      - PMA_ARBITRARY=1