version: "3.9"

volumes:
  dev_database_data:

services:
  # discord:
  #   build: .

  database:
    image: mysql/mysql-server
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_DATABASE=$DB_NAME
      - MYSQL_USER=$DB_AUTH_USER
      - MYSQL_PASSWORD=$DB_AUTH_PASS
      - MYSQL_ROOT_PASSWORD=$DB_AUTH_PASS
      - MYSQL_ROOT_HOST=$DB_ROOT_HOST
    ports:
      - "3306:3306"
    volumes:
      - dev_database_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - "8001:80"
    environment:
      - PMA_ARBITRARY=1