name: Deploy To Production

on:
  push:
    branches:
      - main

jobs:
  build:
    environment: prod

    runs-on: docker

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 18.x
    - run: yarn install --frozen-lockfile
    - run: yarn build
    - run: yarn test

    - name: RSync to server
      uses: https://github.com/D3rHase/rsync-deploy-action@v0.2
      with:
        HOST: ${{ secrets.SSH_HOST }}
        PORT: ${{ secrets.SSH_PORT }}
        USER: ${{ secrets.SSH_USER }}
        PRIVATE_SSH_KEY: ${{ secrets.SSH_KEY }}
        REPOSITORY_PATH: ${{ secrets.PROD_SSH_REPO_PATH }}
        SERVER_PATH: ${{ secrets.PROD_SSH_SERVER_PATH }}

  deploy:
    environment: prod
    needs: build
    runs-on: docker
    steps:
    - uses: https://github.com/appleboy/ssh-action@v1.0.0
      env:
        DB_NAME: ${{ secrets.PROD_DB_NAME }}
        DB_AUTH_USER: ${{ secrets.PROD_DB_AUTH_USER }}
        DB_AUTH_PASS: ${{ secrets.PROD_DB_AUTH_PASS }}
        DB_HOST: ${{ secrets.PROD_DB_HOST }}
        DB_PORT: ${{ secrets.PROD_DB_PORT }}
        DB_ROOT_HOST: ${{ secrets.PROD_DB_ROOT_HOST }}
        DB_SYNC: ${{ secrets.PROD_DB_SYNC }}
        DB_LOGGING: ${{ secrets.PROD_DB_LOGGING }}
        DB_DATA_LOCATION: ${{ secrets.PROD_DB_DATA_LOCATION }}
        SERVER_PATH: ${{ secrets.PROD_SSH_SERVER_PATH }}
        BOT_TOKEN: ${{ secrets.PROD_BOT_TOKEN }}
        BOT_VER: ${{ vars.PROD_BOT_VER }}
        BOT_AUTHOR: ${{ vars.PROD_BOT_AUTHOR }}
        BOT_OWNERID: ${{ vars.PROD_BOT_OWNERID }}
        BOT_CLIENTID: ${{ vars.PROD_BOT_CLIENTID }}
        ABOUT_FUNDING: ${{ vars.PROD_ABOUT_FUNDING }}
        ABOUT_REPO: ${{ vars.PROD_ABOUT_REPO }}
        CACHE_INTERVAL: ${{ vars.PROD_CACHE_INTERVAL }}
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_KEY }}
        port: ${{ secrets.SSH_PORT }}
        envs: DB_NAME,DB_AUTH_USER,DB_AUTH_PASS,DB_HOST,DB_PORT,DB_ROOT_HOST,DB_SYNC,DB_LOGGING,DB_DATA_LOCATION,BOT_TOKEN,BOT_VER,BOT_AUTHOR,BOT_OWNERID,BOT_CLIENTID,ABOUT_FUNDING,ABOUT_REPO,CACHE_INTERVAL
        script: |
          cd /home/vylpes/apps/vylbot/vylbot_prod \
          && docker compose down \
          && (pm2 stop vylbot_prod || true) \
          && (pm2 delete vylbot_prod || true) \
          && docker compose up -d \
          && sleep 10 \
          && yarn run db:up \
          && pm2 start --name vylbot_prod dist/vylbot.js