name: Test

on:
  push:
    branches:
      - feature/*
      - renovate/*

jobs:
  build:
    environment: stage

    runs-on: node

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 18.x
    - run: yarn install --frozen-lockfile
    - run: yarn build
    - run: yarn test