name: integration

on:
  push:
    branches:
      - feature/*
      - hotfix/*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build and Test
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - run: yarn install --frozen-lockfile
      - run: yarn build
      - run: yarn test